# Generated by Django 4.2.4 on 2023-08-11 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Khoj_the_search_Page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputdata',
            old_name='timetamp',
            new_name='timestamp',
        ),
    ]
